# eureka:
#  client:
#   registerWithEureka: true
#   fetchRegistry: true
#   serviceUrl:
#    defaultZone: http://localhost:8070/eureka/ 

server:
  port: 9001
  shutdown: graceful
  

spring:
  application:
    name: catalog-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  
---
spring:
  data:
    cassandra:
      keyspace-name: reactive
      port: 9042
      contact-points:
      - cassandra-catalog
      local-datacenter: datacenter1
---
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://myapp-keycloaks:8080/realms/ecomappProductshop      
        
  

management:
  endpoints:
    web:
      exposure:
        include: refresh
