eureka:
 client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
   defaultZone: http://localhost:8070/eureka/ 

server:
  port: 9001
  shutdown: graceful
  

spring:
  application:
    name: catalog-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  
---
spring:
  data:
    cassandra:
      keyspace-name: reactive
      port: 9042
      contact-points:
      - 127.0.0.1
      local-datacenter: datacenter1
        
  

management:
  endpoints:
    web:
      exposure:
        include: refresh
