
version: "3.8"
services:

  polar-redis:
    image: "redis:7.0"
    container_name: "reactive-redis"
    ports:
      - 6379:6379
  myapp-keycloak:
    image: quay.io/keycloak/keycloak:18.0
    container_name: "myapp-keycloak"
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=KEYCLOAK_ADMIN_PASSWORD
    ports:
      - 8080:8080    
        