
version: "3.8"
services:
  catalog-service:
    depends_on:
      - cassandra-catalog
      - config-service
    image: "catalog-service"
    container_name: "catalog-service"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      # Buildpacks environment variable to configure the number of threads in memory calculation
      - BPL_JVM_THREAD_COUNT=50
      # Buildpacks environment variable to enable debug through a socket on port 8001
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888

  order-service:
    depends_on:
      - cassandra-order
      - config-service
    image: "order-service"
    container_name: "order-service"
    ports:
      - 9002:9002
      - 8002:8002
    environment:
      # Buildpacks environment variable to enable debug through a socket on port 8002
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8002
      - CATALOG_SERVICE_URI=http://catalog-service:9001
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
          
  edge-service:
    depends_on:
      - myapp-redis
    image: "edge-service"
    container_name: "edge-service"
    ports:
      - 9000:9000
      - 8000:8000
    environment:
      # Buildpacks environment variable to enable debug through a socket on port 8000
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8000
      - CATALOG_SERVICE_URL=http://catalog-service:9001
      - ORDER_SERVICE_URL=http://order-service:9002
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_REDIS_HOST=myapp-redis    
  
  config-service:
    image: "config-service"
    container_name: "config-service"
    ports:
      - 8888:8888
      - 9888:9888
    environment:
      # Buildpacks environment variable to configure the number of threads in memory calculation
      - BPL_JVM_THREAD_COUNT=50
      # Buildpacks environment variable to enable debug through a socket on port 9888
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=9888

  cassandra-catalog:
    image: cassandra:3.1
    ports:
      - 9042:9042
    volumes:
      - ~/apps/cassandra:/var/lib/cassandra 

  cassandra-order:
    image: cassandra:3.1
    ports:
      - 9043:9042
    volumes:
      - ~/apps/cassandra:/var/lib/cassandra      

  myapp-redis:
    image: "redis:7.0"
    container_name: "reactive-redis"
    ports:
      - 6379:6379

  myapp-keycloak:
    image: quay.io/keycloak/keycloak:18.0
    container_name: "myapp-keycloak"
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=KEYCLOAK_ADMIN_PASSWORD
    ports:
      - 8080:8080    
        